server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  client:
    #Eureka Client가 아닌 Eureka Server로 동작할 것이므로 registry에 등록하지 않도록 설정
    register-with-eureka: false
    fetch-registry: false
  server:
    #lease-renewal-interval-in-seconds: 1 # 디스커버리한테 1초마다 하트비트 전송(기본 30초)
    #lease-expiration-duration-in-seconds: 2 # 디스커버리는 서비스 등록 해제 하기 전에 마지막 하트비트에서부터 2초 기다림
    #enableSelfPreservation: false  #자기보존모드 비활성화
    #response-cache-update-interval-ms: 3000
