server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          #uri: file:///C:\dev\git-local-repo  # git repository 와 연동 되도록 변경
          uri: https://github.com/todojinu/spring-cloud-config  # url을 입력하여 git repository와 연동
          #private repository인 경우 username과 password 추가
          #username: [your username]
          #password: [password]